### ISSUE TITLE
More input for the Reported Problem of the FM function

### ISSUE THREAD

**Issue by xaiser** [whober0521/CSE6329#2]
We need more input for the viewproblems_fm.html page

- Start date (defaults to today)
- Start time (default to now)
- Facility Type (defaults to MR rooms)
- Facility Name (defaults to null)
- Assigned to username (defaults to null)
- MAR number (defaults to null)

**Comment by vidisha566** [comment]
Can you please explain the 2nd, 4th and 5th issue so that I have a clearer picture?
